<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lbo_glossary"
 *
 * Auto generated by Extension Builder 2017-08-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'A11y Glossary',
    'description'      => '',
    'category'         => 'plugin',
    'author'           => 'Pierre Boivin, Cyril Janody',
    'author_email'     => 'pierre.boivin@libeo.com, cyril.janody@libeo.com',
    'author_compagny'  => 'Libéo, Libéo',
    'state'            => 'stable',
    'internal'         => '',
    'uploadfolder'     => '0',
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '1.0.0',
    'constraints'      => [
        'depends'   => [
            'typo3' => '6.2.0-8.7.99',
        ],
        'conflicts' => [
        ],
        'suggests'  => [
        ],
    ],
    'autoload'         => [
        'psr-4' => [
            'Libeo\\LboGlossary\\' => 'Classes',
        ],
    ],
];